Name: farm-frenzy
Version: 1.0
Release: 3
# Tarball generated from installing the game available at the download
# URL by running
# WINEPREFIX=/usr/lib/games/Fram-Frenzy wine farmfrenzy_setup_full.exe
# cd /usr/lib/games/Farm-Frenzy
# remove-unnecessary-wine-bits
# cd ..
# tar cJf farm-frenzy.tar.xz Farm-Frenzy
Source0: farm-frenzy.tar.xz
# Tarball generated by running
# (after installing the game with wine as described above)
Source1: farm-frenzy-icons.tar.xz
Source2: winegame.c
# Used for creating source tarball, see above
Source3: remove-unnecessary-wine-bits
Summary: Farming game
URL: http://www.myplaycity.com/farm_frenzy/
License: Distributable
Group: Games/Arcade
ExclusiveArch: %{ix86} x86_64
%ifarch %{ix86}
Requires: wine
%else
Requires: wine32
# We need the 32bit version of ALSA's pulseaudio plugin
Requires: libalsa-plugins-pulseaudio
%endif

%description
Have you ever been at a farm?
Animals are all around, walking and looking for food.

And what if you get an opportunity to run your own farm?
Will you cope with it?

There is nothing more pleasant than being in a peaceful country and
enjoying the wind blowing. And here is good news - no awful smells
are waiting for you at Farm Frenzy! You just put on your old boots
and start working.

There is plenty to do at Farm Frenzy. You have 5 animals to take care
of: feed them at the proper time and your geese will bring you eggs.
By selling them you'll get money that helps you to buy new equipment.
What other ways are there to increase income? Once a cheesy dairy appears
at your farm processing milk is possible there - and more money will come.
New tasks give new opportunities: passing level by level you'll learn how
to collect eggs and even coping with a bear and so your farm will become
well-equipped. Use the shop to buy something that can help you produce
more goods for selling and to keep them under good conditions.

Control the animals and become a well-known farmer at the town market.
Make a real business taking into consideration all the factors.

Farm Frenzy is a funny relaxing game full of colors and vivid sounds.
Once you start you can't stop anymore. The gameplay is so entertaining
and the tasks are so challenging that you want this pleasure to last
as long as possible. Why don't you try it right now?

%install
mkdir -p %{buildroot}%{_prefix}/lib/games
cd %{buildroot}%{_prefix}/lib/games
tar xf %{SOURCE0}

mkdir -p %{buildroot}%{_datadir}/icons/hicolor
cd %{buildroot}%{_datadir}/icons/hicolor
tar xf %{SOURCE1}

mkdir -p %{buildroot}%{_bindir}
%__cc %{optflags} -DGAMEPATH=\"%{_prefix}/lib/games/Farm-Frenzy/dosdevices/c:/Program\ Files/Farm\ Frenzy\" -o %{buildroot}%{_bindir}/%{name} %{SOURCE2}

mkdir -p %{buildroot}%{_datadir}/applications
cat >%{buildroot}%{_datadir}/applications/%{name}.desktop <<'EOF'
[Desktop Entry]
Name=Farm Frenzy
Description=Farming Game
Exec=%{_bindir}/%{name}
Type=Application
StartupNotify=true
Icon=A557_game_icon.0
EOF

%files
%attr(6755,root,root) %{_bindir}/%{name}
%dir %{_prefix}/lib/games/Farm-Frenzy
%attr(0664,root,games) %{_prefix}/lib/games/Farm-Frenzy/*.reg
%{_prefix}/lib/games/Farm-Frenzy/drive_c
%{_prefix}/lib/games/Farm-Frenzy/dosdevices
%{_prefix}/lib/games/Farm-Frenzy/.update-timestamp
%{_datadir}/applications/*.desktop
%{_datadir}/icons/hicolor/*/*/*
